version: '3.8'
services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:sqlserver://sqlserver:1433;databaseName=user;encrypt=true;trustServerCertificate=true
      DB_USER: sa
      DB_PASSWORD: YourStrong!Passw0rd
      ACTIVEMQ_URL: tcp://activemq:61616
      KEYCLOAK_URL: http://keycloak:9999
      KEYCLOAK_REALM: development
