CREATE TABLE FAMILY_ENTITY (
    ID          BIGINT IDENTITY(1,1) PRIMARY KEY,
    HOLDER_ID   VARCHAR(36)  NOT NULL,
    NAME        VARCHAR(100) NOT NULL,
    CREATED_AT  DATETIME2    NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT fk_FAMILY_HOLDER FOREIGN KEY (HOLDER_ID) REFERENCES USER_ENTITY(ID)
);
CREATE INDEX IDX_FAMILY_HOLDER ON FAMILY_ENTITY(HOLDER_ID);

CREATE TABLE FAMILY_MEMBER (
    ID          BIGINT IDENTITY(1,1) PRIMARY KEY,
    FAMILY_ID   BIGINT       NOT NULL,
    USER_ID     VARCHAR(36)  NOT NULL,
    JOINED_AT   DATETIME2    NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT fk_member_FAMILY FOREIGN KEY (FAMILY_ID) REFERENCES FAMILY_ENTITY(ID),
    CONSTRAINT fk_member_USER   FOREIGN KEY (USER_ID)   REFERENCES USER_ENTITY(ID),
    CONSTRAINT uq_member_USER   UNIQUE (USER_ID),
    CONSTRAINT uq_member_FAMILY_USER UNIQUE (FAMILY_ID, USER_ID)
);
CREATE INDEX IDX_FAMILY_MEMBER_FAMILY ON FAMILY_MEMBER(FAMILY_ID);
CREATE INDEX IDX_FAMILY_MEMBER_USER ON FAMILY_MEMBER(USER_ID);
